Use shell function for new apps

diff --git a/ocean/templates/initd b/ocean/templates/initd
--- a/ocean/templates/initd
+++ b/ocean/templates/initd
@@ -1,11 +1,11 @@
 #!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          {{ name }}
+# Provides:          APP_NAME
 # Required-Start:    $local_fs $network $named $time $syslog
 # Required-Stop:     $local_fs $network $named $time $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Description:       Manages app {{ name }}
+# Description:       Manages app APP_NAME
 ### END INIT INFO
 
 export RAILS_ENV='production'
@@ -14,32 +14,32 @@ export NODE_ENV='production'
 SCRIPT='echo "run app command here"'
 RUNAS=root
 
-PIDFILE=/var/run/{{ name }}.pid
-LOGFILE=/var/log/{{ name }}.log
+PIDFILE=/var/run/APP_NAME.pid
+LOGFILE=/var/log/APP_NAME.log
 
 start() {
   if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
-    echo 'Service {{ name }} already running' >&2
+    echo 'Service APP_NAME already running' >&2
     return 1
   fi
-  echo 'Starting service {{ name }}' >&2
+  echo 'Starting service APP_NAME' >&2
   local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
   su -c "$CMD" $RUNAS > "$PIDFILE"
-  echo 'Service {{ name }} started' >&2
+  echo 'Service APP_NAME started' >&2
 }
 
 stop() {
   if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
-    echo 'Service {{ name }} not running' >&2
+    echo 'Service APP_NAME not running' >&2
     return 1
   fi
-  echo 'Stopping service {{ name }}' >&2
+  echo 'Stopping service APP_NAME' >&2
   kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
-  echo 'Service {{ name }} stopped' >&2
+  echo 'Service APP_NAME stopped' >&2
 }
 
 uninstall() {
-  echo -n "Are you really sure you want to uninstall service {{ name }}? That cannot be undone. [yes|No] "
+  echo -n "Are you really sure you want to uninstall service APP_NAME? That cannot be undone. [yes|No] "
   local SURE
   read SURE
   if [ "$SURE" = "yes" ]; then
